export const categories = [
  'Content',
  'Crafting',
  'Logistics',
  'Hospitality',
  'Provisioning',
  'Responders',
  'Services',
  'Specialists',
  'Various',
]
export const professions: any = {
  '': null,
  Content: [
    'Editor',
    'Journalist',
    'Musician',
    'Promoter',
    'Publisher',
    'Writer',
  ],
  Crafting: ['Artisan', 'Artist', 'Builder', 'Fabricator', 'Tinker'],
  Logistics: ['Biker', 'Courier', 'Mover', 'Scout'],
  Hospitality: ['Bard', 'BnB Host', 'Comedian', 'Concierge', 'Guide', 'Jester'],
  Provisioning: [
    'Baker',
    'Bartender',
    'Caterer',
    'Chef',
    'Farmer',
    'Herbalist',
    'Horticulturist',
    'Merchant',
  ],
  Responders: ['Constable', 'Fighter', 'Guardian', 'Medic'],
  Services: ['Caregiver', 'Cleaner', 'Nurse'],
  Specialists: [
    'Architect',
    'Dancer',
    'Designer',
    'Engineer',
    'Entrepreneur',
    'Programmer',
    'Scholar',
    'Scientist',
    'Teacher',
    'Technician',
  ],
  Various: ['Cleric', 'Druid', 'Monk', 'Ranger', 'Shaman', 'Wizard'],
}
